# Generated by Django 2.2.6 on 2019-10-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20191027_2350'),
    ]

    operations = [
    ]
